--TESTING
ACCEPT v_agentID NUMBER PROMPT "Enter Agent ID: ";
ACCEPT v_FDate Date FORMAT 'dd-mm-yyyy' PROMPT "Enter Form Date (dd-mm-yyyy): ";
ACCEPT v_TDate Date FORMAT 'dd-mm-yyyy' PROMPT "Enter To Date (dd-mm-yyyy): ";


Accept onum number PROMPT "ENTER O NUM :"
Accept dd Date FORMAT 'dd-mm-yyyy' PROMPT "ENTER dd :"
select customerNumber from orders where ordernumber=&onum and requiredDate=&dd;



select customerNumber from orders where ordernumber='&num' and requiredDate=to_date('&Enter_Date','mm/dd/yyyy');
to_date('&Enter_Date','mm/dd/yyyy');


---REAL USE

asgmt/asgmt@localhost:1521/xepdb1
Select table_name from user_tables;
ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD';


--Travel Agent
CREATE TABLE Travel_Agent  (
  Agent_ID INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 INCREMENT BY 1,
  Agent_Name VARCHAR2(50) NOT NULL,
  Agent_Phone VARCHAR2(30) NOT NULL,
  Agent_Email VARCHAR2(50) NOT NULL,
  Agent_Gender CHAR(1) NOT NULL,
  Agent_Address VARCHAR2(100) NOT NULL,
  DoB Date NOT NULL,
PRIMARY KEY (Agent_ID)
)

CREATE TABLE Enquiry (
  Enquiry_ID INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 INCREMENT BY 1,
  Enquiry_Desc VARCHAR2(1000) NOT NULL,
  Enquiry_Date Date NOT NULL,
  Agent_Reply VARCHAR2(1000),	
  Cust_Rating INT NOT NULL,
  Cust_Experience VARCHAR2(1000),
  Cust_ID INT NOT NULL,
  Agent_ID INT,
  PRIMARY KEY (Enquiry_ID),
  CONSTRAINT FK_Travel_Agent FOREIGN KEY (Agent_ID) REFERENCES Travel_Agent(Agent_ID)
);
--Test Later
Cust_ID int FOREIGN KEY REFERENCES Customer(Cust_ID),




--Enquiry
CREATE TABLE Enquiry (

Enquiry_ID		INT			IDENTITY (1, 1) NOT NULL,
Enquiry_Desc    	VARCHAR2(1000) 	NOT NULL,
Enquiry_Date     	Date			NOT NULL,
Agent_Reply   	VARCHAR2(1000),	
Cust_Rating   		INT 			NOT NULL,
Cust_Experience 	VARCHAR2(1000),	
Cust_ID		INT,
Agent_ID		INT,

PRIMARY KEY (Enquiry_ID),
Cust_ID int FOREIGN KEY REFERENCES Customer(Cust_ID),
Agent_ID int FOREIGN KEY REFERENCES Travel Agent(Agent_ID)
);




SELECT AGENT_ID FROM TRAVEL_AGENT;
