
CREATE TABLE Driver(
	Driver_ID Int NOT NULL,
	Driver_Name Varchar2(10) NOT NULL,
	Driver_Age Int NOT NULL,
	Licence Varchar2(10) NOT NULL,
	Join_Date Date NOT NULL,
	PRIMARY KEY (Driver_ID)
);

CREATE TABLE Tourism_Vehicle(
	Vehicle_ID INT NOT NULL,
	Model Varchar2(10) NOT NULL,
	Plate_Number Varchar2(8) NOT NULL,
        Driver_ID INT NOT NULL,
	PRIMARY KEY (Vehicle_ID),
	FOREIGN KEY (Driver_ID)  REFERENCES Driver(Driver_ID)  
);

CREATE TABLE Bus_Schedule(
	Bus_Schedule_ID  INT NOT NULL,
	Depart Date NOT NULL,
	Arrival Date NOT NULL,
	Vehicle_ID INT NOT NULL,
	PRIMARY KEY (Bus_Schedule_ID),
	FOREIGN KEY(Vehicle_ID) REFERENCES Tourism_Vehicle(Vehicle_ID) 
);

CREATE TABLE Tour (
	Tour_ID int NOT NULL,
	Destination varchar2(200) NOT NULL,
	Tour_Desc varchar2(1000),
	PRIMARY KEY(Tour_ID)
);

CREATE TABLE travel_package (
	Package_ID INT NOT NULL,
	Package_Name varchar2(200) NOT NULL,  
	Price Number(7,2) NOT NULL,
	Seat INT NOT NULL CHECK(Seat BETWEEN 20 AND 60),
        Tour_ID INT NOT NULL,
        Bus_Schedule_ID INT NOT NULL,
	PRIMARY KEY (Package_ID),
	FOREIGN KEY (Tour_ID) REFERENCES Tour (Tour_ID),
	FOREIGN KEY (Bus_Schedule_ID) REFERENCES Bus_Schedule (Bus_Schedule_ID)
);

CREATE TABLE Travel_Agent  (
	Agent_ID 		INT 			GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 INCREMENT BY 1,
	Agent_Name 		VARCHAR2(50) 	NOT NULL,
	Agent_Phone 		VARCHAR2(30) 	NOT NULL,
	Agent_Email 		VARCHAR2(50) 	NOT NULL,
	Agent_Gender 	CHAR(1) 		NOT NULL,
	Agent_Address 	VARCHAR2(100) 	NOT NULL,
	DoB 			Date 			NOT NULL,
	PRIMARY KEY (Agent_ID)
);

CREATE TABLE Package_Schedule (
	Package_Schedule_ID int NOT NULL,
	Start_Date date NOT NULL,
	End_Date date NOT NULL,
	Schedule_Remark varchar2(1000),
	Seat_Available int NOT NULL ,
	Available_Status varchar2(10) NOT NULL, 
        Agent_ID INT NOT NULL,
        Package_ID INT NOT NULL,
	PRIMARY KEY(Package_Schedule_ID),
	FOREIGN KEY (Agent_ID) REFERENCES Travel_Agent (Agent_ID),
	FOREIGN KEY (Package_ID) REFERENCES Travel_Package (Package_ID)
);

CREATE TABLE Tourism_Customer (
	Cust_ID		 INT		 NOT NULL,
	Cust_Name		 VARCHAR2(50),  
            Cust_Gender		 Char(1),  
	Cust_Address		 VARCHAR2(200),
	Cust_Phone 		 VARCHAR2(10),
	DoB 			 DATE,
	PRIMARY KEY (Cust_ID)
);

CREATE TABLE Booking (
	Booking_ID		 INT		 NOT NULL,
	Booking_Date		 DATE,  
        Cust_ID		 INT,  
	PRIMARY KEY (Booking_ID),
	FOREIGN KEY (Cust_ID) REFERENCES Tourism_Customer (Cust_ID)
);


CREATE TABLE Enquiry (
	Enquiry_ID 		INT 			GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 INCREMENT BY 1,
	Enquiry_Desc 		VARCHAR2(1000) 	NOT NULL,
	Enquiry_Date 		Date 			NOT NULL,
	Agent_Reply 		VARCHAR2(1000),	
	Cust_Rating 		INT 			NOT NULL,
	Cust_Experience 	VARCHAR2(1000),
	Cust_ID 		INT 			NOT NULL,
	Agent_ID 		INT                     NOT NULL,
	PRIMARY KEY (Enquiry_ID),
	CONSTRAINT FK_Travel_Agent FOREIGN KEY (Agent_ID) REFERENCES Travel_Agent(Agent_ID),
	CONSTRAINT FK_Customer_ID FOREIGN KEY (Cust_ID) REFERENCES Tourism_Customer(Cust_ID)
);


CREATE TABLE Booking_Details (
        Detail_ID  INT NOT NULL, 
	Booking_ID  INT NOT NULL,
 	Package_Schedule_ID   INT NOT NULL,
	Seat_Booked		 	 INT,  
        Sub_Total_Price	 	 NUMBER(7, 2),  
 	Booking_Status 		 VARCHAR(10),
	PRIMARY KEY (Detail_ID),
	FOREIGN KEY (Booking_ID) REFERENCES Booking(Booking_ID),
   	FOREIGN KEY (Package_Schedule_ID ) REFERENCES Package_Schedule(Package_Schedule_ID )
);


drop table Booking_Details;
drop table Enquiry;
drop table Booking;
drop table Tourism_Customer;
drop table Package_Schedule;
drop table Travel_Agent;
drop table travel_package;
drop table Tour;
drop table Bus_Schedule;
drop table Tourism_Vehicle;
drop table driver;

--delete all information
declare
  cursor c_t is (select table_name from user_tables);
  table_name user_tables.table_name%type;
begin 
  open c_t;
  loop
       fetch c_t into table_name;
       exit when c_t%notfound;
       execute immediate 'delete from ' || table_name;
  end loop;
  close c_t;
end;

alter table Travel_Agent
modify Agent_ID generated always as identity restart start with 1000;


CREATE TABLE travel_package (
	Package_ID INT NOT NULL,
	Package_Name varchar2(200) NOT NULL,  
	Price Number(7,2) NOT NULL,
	Seat INT,
    Tour_ID INT NOT NULL,
    Bus_Schedule_ID INT NOT NULL,
	PRIMARY KEY (Package_ID)
);

CREATE TABLE Package_Schedule (
	Package_Schedule_ID int NOT NULL,
	Start_Date date NOT NULL,
	End_Date date NOT NULL,
	Schedule_Remark varchar2(1000),
	Seat_Available int NOT NULL ,
	Available_Status varchar2(6) NOT NULL, 
    Agent_ID INT NOT NULL,
    Package_ID INT NOT NULL	
);





