CREATE TABLE Travel_Agent  (
Agent_ID INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 INCREMENT BY 1,
Agent_Name VARCHAR2(50) NOT NULL,
Agent_Phone VARCHAR2(30) NOT NULL,
Agent_Email VARCHAR2(50) NOT NULL,
Agent_Gender CHAR(1) NOT NULL,
Agent_Address VARCHAR2(100) NOT NULL,
DoB Date NOT NULL,
PRIMARY KEY (Agent_ID)
)
--In auto increment if you wanna to delete whole table data you should reset the idenetity.
--trigger can automate do the adjusting on it
--For travel agent
delete from Travel_Agent;
alter table Travel_Agent modify Agent_ID generated always as identity restart start with 1000;



Insert into Travel_Agent(AGENT_NAME,AGENT_PHONE,AGENT_EMAIL,AGENT_GENDER,AGENT_ADDRESS,DOB) 
VALUES('Alfreds Futterkiste','01117601411','Alfreds@gmail.com','M','Jalan Pjs 11/2, Taman Subang Indah,Petaling Jaya,Selangor',TO_DATE('2000-01-06','YYYY-MM-DD'));

Insert into Travel_Agent(AGENT_NAME,AGENT_PHONE,AGENT_EMAIL,AGENT_GENDER,AGENT_ADDRESS,DOB) 
VALUES('Tempawan bin Ayu','0127954488','Tempawan@gmail.com','M','kPelangi condo, Jln Gong Badak,Petaling Jaya,Selangor',TO_DATE('1995-07-06','YYYY-MM-DD'));

Insert into Travel_Agent(AGENT_NAME,AGENT_PHONE,AGENT_EMAIL,AGENT_GENDER,AGENT_ADDRESS,DOB) 
VALUES('Zhang Tam Cheng','0116588740','zhaneng@gmail.com','F','Jalan Jelutong 7/5P, Medan Brickfields, 58231 Bandar Tasik Selatan, WP Kuala Lumpur',TO_DATE('2000-01-06','YYYY-MM-DD'));

Insert into Travel_Agent(AGENT_NAME,AGENT_PHONE,AGENT_EMAIL,AGENT_GENDER,AGENT_ADDRESS,DOB) 
VALUES('Koh Deng Kap','0155473921','kohdap@gmail.com','M','Jln Davis 3, PJU3, 66079 Banting, Selangor Darul Ehsan',TO_DATE('1996-06-23','YYYY-MM-DD'));

Insert into Travel_Agent(AGENT_NAME,AGENT_PHONE,AGENT_EMAIL,AGENT_GENDER,AGENT_ADDRESS,DOB) 
VALUES('Nur Alis binti Nik Hakimie','0116516065','nuuramie@gmail.com','F','Jalan 6K, Bandar Kerinchi,Petaling Jaya,Selangor',TO_DATE('1997-07-06','YYYY-MM-DD'));

Insert into Travel_Agent(AGENT_NAME,AGENT_PHONE,AGENT_EMAIL,AGENT_GENDER,AGENT_ADDRESS,DOB) 
VALUES('Rani Vadaketh','0110806011','ranith@gmail.com','F','Jalan 7T, PJU7,11235 Butterworth,Petaling Jaya,Selangor',TO_DATE('1997-01-26','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Georg Baudouin', '3746037819', 'gbaudouin0@over-blog.com', 'M', '859 Sommers Plaza', TO_DATE('1999-10-30','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Batholomew Hallifax', '3247038466', 'bhallifax1@sohu.com', 'M', '6827 Lake View Terrace', TO_DATE('1991-10-11','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Korrie Reyne', '4685601511', 'kreyne2@wikimedia.org', 'F', '28356 Lawn Way', TO_DATE('1991-02-21','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Petronilla Chugg', '6392134582', 'pchugg3@japanpost.jp', 'F', '90 Merry Plaza', TO_DATE('1994-10-01','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Kettie Drysdale', '6861423671', 'kdrysdale4@psu.edu', 'F', '3268 Everett Way', TO_DATE('1996-03-28','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Allegra Lidgely', '1772278661', 'alidgely5@amazon.com', 'F', '407 Glacier Hill Lane', TO_DATE('1990-12-28','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Georas Ickowics', '7297920355', 'gickowics6@instagram.com', 'M', '9 Helena Plaza', TO_DATE('1991-07-02','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Bride Nelissen', '1966729775', 'bnelissen7@phpbb.com', 'F', '048 Novick Avenue', TO_DATE('2000-05-09','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Phil Sex', '3393471096', 'psex8@xrea.com', 'M', '44 Havey Center', TO_DATE('1990-06-13','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Nate Bockin', '9468600303', 'nbockin9@prlog.org', 'M', '4813 Brickson Park Park', TO_DATE('1992-03-05','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Kally Cambling', '8284664470', 'kcamblinga@mozilla.org', 'F', '520 Little Fleur Drive', TO_DATE('1992-11-22','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Petronille Kalinowsky', '6194921543', 'pkalinowskyb@mediafire.com', 'F', '6660 Stone Corner Way', TO_DATE('1995-01-02','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Roberta Branson', '9082080417', 'rbransonc@google.de', 'F', '2 Carioca Park', TO_DATE('1999-01-15','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Winston Selwood', '1857388262', 'wselwoodd@princeton.edu', 'M', '2 Sutteridge Circle', TO_DATE('1997-07-25','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Mab Piburn', '9852822454', 'mpiburne@mtv.com', 'F', '83481 Portage Street', TO_DATE('2000-04-19','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Estele Eppson', '3106560770', 'eeppsonf@yellowpages.com', 'F', '3 Little Fleur Pass', TO_DATE('1997-04-16','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Munroe Atrill', '4047442587', 'matrillg@yellowpages.com', 'M', '0993 Bellgrove Parkway', TO_DATE('1999-10-05','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Elsworth Targetter', '8198477420', 'etargetterh@usgs.gov', 'M', '2120 Hansons Pass', TO_DATE('1997-06-15','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Toiboid Cassels', '4844499404', 'tcasselsi@networkadvertising.org', 'M', '9283 Mandrake Street', TO_DATE('1999-01-16','YYYY-MM-DD'));

insert into Travel_Agent (Agent_Name, Agent_Phone, Agent_Email, Agent_Gender, Agent_Address, DoB ) 
values ('Margy Wong', '0127798388', 'mWongj@npr.org', 'F', '750 Redwing Court',TO_DATE('1992-12-27','YYYY-MM-DD'));


--wrong data
Insert into Travel_Agent(AGENT_NAME,AGENT_PHONE,AGENT_EMAIL,AGENT_GENDER,AGENT_ADDRESS,DOB) 
VALUES('Albert Wong','01117601411','Alfredsgmail.com','M','Jalan Pjs 11/2, Taman Subang Indah,Petaling Jaya,Selangor',TO_DATE('2000-01-06','YYYY-MM-DD'));